<?php

namespace ContainerEzOmrSx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KbgLu53Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kbgLu53' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kbgLu53'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiEvenementController::index' => ['privates', '.service_locator.JHUmu2_', 'get_ServiceLocator_JHUmu2Service', true],
            'App\\Controller\\ApiEvenementController::maj' => ['privates', '.service_locator.sP6DrBB', 'get_ServiceLocator_SP6DrBBService', true],
            'App\\Controller\\ApiEvenementController::store' => ['privates', '.service_locator.sP6DrBB', 'get_ServiceLocator_SP6DrBBService', true],
            'App\\Controller\\ApiEvenementController::supp' => ['privates', '.service_locator.sP6DrBB', 'get_ServiceLocator_SP6DrBBService', true],
            'App\\Controller\\ApiInscriptionController::store' => ['privates', '.service_locator.mtoGLzc', 'get_ServiceLocator_MtoGLzcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ApiEvenementController:index' => ['privates', '.service_locator.JHUmu2_', 'get_ServiceLocator_JHUmu2Service', true],
            'App\\Controller\\ApiEvenementController:maj' => ['privates', '.service_locator.sP6DrBB', 'get_ServiceLocator_SP6DrBBService', true],
            'App\\Controller\\ApiEvenementController:store' => ['privates', '.service_locator.sP6DrBB', 'get_ServiceLocator_SP6DrBBService', true],
            'App\\Controller\\ApiEvenementController:supp' => ['privates', '.service_locator.sP6DrBB', 'get_ServiceLocator_SP6DrBBService', true],
            'App\\Controller\\ApiInscriptionController:store' => ['privates', '.service_locator.mtoGLzc', 'get_ServiceLocator_MtoGLzcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ApiEvenementController::index' => '?',
            'App\\Controller\\ApiEvenementController::maj' => '?',
            'App\\Controller\\ApiEvenementController::store' => '?',
            'App\\Controller\\ApiEvenementController::supp' => '?',
            'App\\Controller\\ApiInscriptionController::store' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ApiEvenementController:index' => '?',
            'App\\Controller\\ApiEvenementController:maj' => '?',
            'App\\Controller\\ApiEvenementController:store' => '?',
            'App\\Controller\\ApiEvenementController:supp' => '?',
            'App\\Controller\\ApiInscriptionController:store' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
